/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_daml_ledger_api_v1_completion_pb = require('../../../../../com/daml/ledger/api/v1/completion_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_completion_pb);
var com_daml_ledger_api_v1_ledger_offset_pb = require('../../../../../com/daml/ledger/api/v1/ledger_offset_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_ledger_offset_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.com.daml.ledger.api.v1.Checkpoint', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CompletionEndRequest', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CompletionEndResponse', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CompletionStreamRequest', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CompletionStreamResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.CompletionStreamRequest.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CompletionStreamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CompletionStreamRequest.displayName = 'proto.com.daml.ledger.api.v1.CompletionStreamRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.CompletionStreamResponse.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CompletionStreamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CompletionStreamResponse.displayName = 'proto.com.daml.ledger.api.v1.CompletionStreamResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.Checkpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.Checkpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.Checkpoint.displayName = 'proto.com.daml.ledger.api.v1.Checkpoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CompletionEndRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CompletionEndRequest.displayName = 'proto.com.daml.ledger.api.v1.CompletionEndRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CompletionEndResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CompletionEndResponse.displayName = 'proto.com.daml.ledger.api.v1.CompletionEndResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CompletionStreamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CompletionStreamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    applicationId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    partiesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    offset: (f = msg.getOffset()) && com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CompletionStreamRequest}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CompletionStreamRequest;
  return proto.com.daml.ledger.api.v1.CompletionStreamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CompletionStreamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CompletionStreamRequest}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addParties(value);
      break;
    case 4:
      var value = new com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset;
      reader.readMessage(value,com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.deserializeBinaryFromReader);
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CompletionStreamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CompletionStreamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApplicationId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getOffset();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.serializeBinaryToWriter
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string application_id = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.getApplicationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.setApplicationId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string parties = 3;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.getPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.setPartiesList = function(value) {
  jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.addParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.clearPartiesList = function() {
  this.setPartiesList([]);
};


/**
 * optional LedgerOffset offset = 4;
 * @return {?proto.com.daml.ledger.api.v1.LedgerOffset}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.getOffset = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.LedgerOffset} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset, 4));
};


/** @param {?proto.com.daml.ledger.api.v1.LedgerOffset|undefined} value */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.setOffset = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.clearOffset = function() {
  this.setOffset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CompletionStreamRequest.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 4) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CompletionStreamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CompletionStreamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    checkpoint: (f = msg.getCheckpoint()) && proto.com.daml.ledger.api.v1.Checkpoint.toObject(includeInstance, f),
    completionsList: jspb.Message.toObjectList(msg.getCompletionsList(),
    com_daml_ledger_api_v1_completion_pb.Completion.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CompletionStreamResponse}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CompletionStreamResponse;
  return proto.com.daml.ledger.api.v1.CompletionStreamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CompletionStreamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CompletionStreamResponse}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.daml.ledger.api.v1.Checkpoint;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.Checkpoint.deserializeBinaryFromReader);
      msg.setCheckpoint(value);
      break;
    case 2:
      var value = new com_daml_ledger_api_v1_completion_pb.Completion;
      reader.readMessage(value,com_daml_ledger_api_v1_completion_pb.Completion.deserializeBinaryFromReader);
      msg.addCompletions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CompletionStreamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CompletionStreamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCheckpoint();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.daml.ledger.api.v1.Checkpoint.serializeBinaryToWriter
    );
  }
  f = message.getCompletionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      com_daml_ledger_api_v1_completion_pb.Completion.serializeBinaryToWriter
    );
  }
};


/**
 * optional Checkpoint checkpoint = 1;
 * @return {?proto.com.daml.ledger.api.v1.Checkpoint}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.getCheckpoint = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Checkpoint} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.Checkpoint, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.Checkpoint|undefined} value */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.setCheckpoint = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.clearCheckpoint = function() {
  this.setCheckpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.hasCheckpoint = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Completion completions = 2;
 * @return {!Array<!proto.com.daml.ledger.api.v1.Completion>}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.getCompletionsList = function() {
  return /** @type{!Array<!proto.com.daml.ledger.api.v1.Completion>} */ (
    jspb.Message.getRepeatedWrapperField(this, com_daml_ledger_api_v1_completion_pb.Completion, 2));
};


/** @param {!Array<!proto.com.daml.ledger.api.v1.Completion>} value */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.setCompletionsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.com.daml.ledger.api.v1.Completion=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.daml.ledger.api.v1.Completion}
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.addCompletions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.com.daml.ledger.api.v1.Completion, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.CompletionStreamResponse.prototype.clearCompletionsList = function() {
  this.setCompletionsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.Checkpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.Checkpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Checkpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    recordTime: (f = msg.getRecordTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    offset: (f = msg.getOffset()) && com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.Checkpoint}
 */
proto.com.daml.ledger.api.v1.Checkpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.Checkpoint;
  return proto.com.daml.ledger.api.v1.Checkpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.Checkpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.Checkpoint}
 */
proto.com.daml.ledger.api.v1.Checkpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setRecordTime(value);
      break;
    case 2:
      var value = new com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset;
      reader.readMessage(value,com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.deserializeBinaryFromReader);
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.Checkpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.Checkpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Checkpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRecordTime();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getOffset();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp record_time = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.getRecordTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.setRecordTime = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.clearRecordTime = function() {
  this.setRecordTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.hasRecordTime = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional LedgerOffset offset = 2;
 * @return {?proto.com.daml.ledger.api.v1.LedgerOffset}
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.getOffset = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.LedgerOffset} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset, 2));
};


/** @param {?proto.com.daml.ledger.api.v1.LedgerOffset|undefined} value */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.setOffset = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.clearOffset = function() {
  this.setOffset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Checkpoint.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CompletionEndRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CompletionEndRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ledgerId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CompletionEndRequest}
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CompletionEndRequest;
  return proto.com.daml.ledger.api.v1.CompletionEndRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CompletionEndRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CompletionEndRequest}
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLedgerId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CompletionEndRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CompletionEndRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLedgerId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string ledger_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.CompletionEndRequest.prototype.getLedgerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.CompletionEndRequest.prototype.setLedgerId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CompletionEndResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CompletionEndResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    offset: (f = msg.getOffset()) && com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CompletionEndResponse}
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CompletionEndResponse;
  return proto.com.daml.ledger.api.v1.CompletionEndResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CompletionEndResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CompletionEndResponse}
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset;
      reader.readMessage(value,com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.deserializeBinaryFromReader);
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CompletionEndResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CompletionEndResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffset();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset.serializeBinaryToWriter
    );
  }
};


/**
 * optional LedgerOffset offset = 1;
 * @return {?proto.com.daml.ledger.api.v1.LedgerOffset}
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.prototype.getOffset = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.LedgerOffset} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_ledger_offset_pb.LedgerOffset, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.LedgerOffset|undefined} value */
proto.com.daml.ledger.api.v1.CompletionEndResponse.prototype.setOffset = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.prototype.clearOffset = function() {
  this.setOffset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CompletionEndResponse.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.com.daml.ledger.api.v1);
