/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_daml_ledger_api_v1_commands_pb = require('../../../../../com/daml/ledger/api/v1/commands_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_commands_pb);
var com_daml_ledger_api_v1_transaction_pb = require('../../../../../com/daml/ledger/api/v1/transaction_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_transaction_pb);
var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
goog.exportSymbol('proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.SubmitAndWaitRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.SubmitAndWaitRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.displayName = 'proto.com.daml.ledger.api.v1.SubmitAndWaitRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.displayName = 'proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.displayName = 'proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.displayName = 'proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    commands: (f = msg.getCommands()) && com_daml_ledger_api_v1_commands_pb.Commands.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitRequest}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.SubmitAndWaitRequest;
  return proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitRequest}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_daml_ledger_api_v1_commands_pb.Commands;
      reader.readMessage(value,com_daml_ledger_api_v1_commands_pb.Commands.deserializeBinaryFromReader);
      msg.setCommands(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommands();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_daml_ledger_api_v1_commands_pb.Commands.serializeBinaryToWriter
    );
  }
};


/**
 * optional Commands commands = 1;
 * @return {?proto.com.daml.ledger.api.v1.Commands}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.prototype.getCommands = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Commands} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_commands_pb.Commands, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.Commands|undefined} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.prototype.setCommands = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.prototype.clearCommands = function() {
  this.setCommands(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitRequest.prototype.hasCommands = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    completionOffset: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse;
  return proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompletionOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCompletionOffset();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string transaction_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.prototype.setTransactionId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string completion_offset = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.prototype.getCompletionOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionIdResponse.prototype.setCompletionOffset = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transaction: (f = msg.getTransaction()) && com_daml_ledger_api_v1_transaction_pb.Transaction.toObject(includeInstance, f),
    completionOffset: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse;
  return proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_daml_ledger_api_v1_transaction_pb.Transaction;
      reader.readMessage(value,com_daml_ledger_api_v1_transaction_pb.Transaction.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompletionOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_daml_ledger_api_v1_transaction_pb.Transaction.serializeBinaryToWriter
    );
  }
  f = message.getCompletionOffset();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional Transaction transaction = 1;
 * @return {?proto.com.daml.ledger.api.v1.Transaction}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.getTransaction = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Transaction} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_transaction_pb.Transaction, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.Transaction|undefined} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.setTransaction = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.clearTransaction = function() {
  this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string completion_offset = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.getCompletionOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionResponse.prototype.setCompletionOffset = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    transaction: (f = msg.getTransaction()) && com_daml_ledger_api_v1_transaction_pb.TransactionTree.toObject(includeInstance, f),
    completionOffset: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse;
  return proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_daml_ledger_api_v1_transaction_pb.TransactionTree;
      reader.readMessage(value,com_daml_ledger_api_v1_transaction_pb.TransactionTree.deserializeBinaryFromReader);
      msg.setTransaction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompletionOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransaction();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_daml_ledger_api_v1_transaction_pb.TransactionTree.serializeBinaryToWriter
    );
  }
  f = message.getCompletionOffset();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional TransactionTree transaction = 1;
 * @return {?proto.com.daml.ledger.api.v1.TransactionTree}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.getTransaction = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.TransactionTree} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_transaction_pb.TransactionTree, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.TransactionTree|undefined} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.setTransaction = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.clearTransaction = function() {
  this.setTransaction(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.hasTransaction = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string completion_offset = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.getCompletionOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.SubmitAndWaitForTransactionTreeResponse.prototype.setCompletionOffset = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.com.daml.ledger.api.v1);
