/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_rpc_status_pb = require('../../../../../google/rpc/status_pb.js');
goog.object.extend(proto, google_rpc_status_pb);
goog.exportSymbol('proto.com.daml.ledger.api.v1.Completion', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.Completion = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.Completion.repeatedFields_, proto.com.daml.ledger.api.v1.Completion.oneofGroups_);
};
goog.inherits(proto.com.daml.ledger.api.v1.Completion, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.Completion.displayName = 'proto.com.daml.ledger.api.v1.Completion';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.Completion.repeatedFields_ = [5];

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.daml.ledger.api.v1.Completion.oneofGroups_ = [[8,9]];

/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.Completion.DeduplicationPeriodCase = {
  DEDUPLICATION_PERIOD_NOT_SET: 0,
  DEDUPLICATION_OFFSET: 8,
  DEDUPLICATION_DURATION: 9
};

/**
 * @return {proto.com.daml.ledger.api.v1.Completion.DeduplicationPeriodCase}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getDeduplicationPeriodCase = function() {
  return /** @type {proto.com.daml.ledger.api.v1.Completion.DeduplicationPeriodCase} */(jspb.Message.computeOneofCase(this, proto.com.daml.ledger.api.v1.Completion.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.Completion.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.Completion} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Completion.toObject = function(includeInstance, msg) {
  var f, obj = {
    commandId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f),
    transactionId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    applicationId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    actAsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    submissionId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    deduplicationOffset: jspb.Message.getFieldWithDefault(msg, 8, ""),
    deduplicationDuration: (f = msg.getDeduplicationDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.Completion}
 */
proto.com.daml.ledger.api.v1.Completion.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.Completion;
  return proto.com.daml.ledger.api.v1.Completion.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.Completion} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.Completion}
 */
proto.com.daml.ledger.api.v1.Completion.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandId(value);
      break;
    case 2:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setApplicationId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addActAs(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubmissionId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeduplicationOffset(value);
      break;
    case 9:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setDeduplicationDuration(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.Completion.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.Completion} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Completion.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommandId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getApplicationId();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getActAsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getSubmissionId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 8));
  if (f != null) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getDeduplicationDuration();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
};


/**
 * optional string command_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getCommandId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setCommandId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional google.rpc.Status status = 2;
 * @return {?proto.google.rpc.Status}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 2));
};


/** @param {?proto.google.rpc.Status|undefined} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setStatus = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Completion.prototype.clearStatus = function() {
  this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string transaction_id = 3;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setTransactionId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string application_id = 4;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getApplicationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setApplicationId = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated string act_as = 5;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getActAsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setActAsList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.Completion.prototype.addActAs = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.Completion.prototype.clearActAsList = function() {
  this.setActAsList([]);
};


/**
 * optional string submission_id = 6;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getSubmissionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setSubmissionId = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string deduplication_offset = 8;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getDeduplicationOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setDeduplicationOffset = function(value) {
  jspb.Message.setOneofField(this, 8, proto.com.daml.ledger.api.v1.Completion.oneofGroups_[0], value);
};


/**
 * Clears the field making it undefined.
 */
proto.com.daml.ledger.api.v1.Completion.prototype.clearDeduplicationOffset = function() {
  jspb.Message.setOneofField(this, 8, proto.com.daml.ledger.api.v1.Completion.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.hasDeduplicationOffset = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Duration deduplication_duration = 9;
 * @return {?proto.google.protobuf.Duration}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.getDeduplicationDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 9));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.com.daml.ledger.api.v1.Completion.prototype.setDeduplicationDuration = function(value) {
  jspb.Message.setOneofWrapperField(this, 9, proto.com.daml.ledger.api.v1.Completion.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Completion.prototype.clearDeduplicationDuration = function() {
  this.setDeduplicationDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Completion.prototype.hasDeduplicationDuration = function() {
  return jspb.Message.getField(this, 9) != null;
};


goog.object.extend(exports, proto.com.daml.ledger.api.v1);
