/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_daml_ledger_api_v1_contract_metadata_pb = require('../../../../../com/daml/ledger/api/v1/contract_metadata_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_contract_metadata_pb);
var com_daml_ledger_api_v1_value_pb = require('../../../../../com/daml/ledger/api/v1/value_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_value_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
var google_rpc_status_pb = require('../../../../../google/rpc/status_pb.js');
goog.object.extend(proto, google_rpc_status_pb);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ArchivedEvent', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CreatedEvent', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.Event', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExercisedEvent', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.InterfaceView', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.Event = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.daml.ledger.api.v1.Event.oneofGroups_);
};
goog.inherits(proto.com.daml.ledger.api.v1.Event, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.Event.displayName = 'proto.com.daml.ledger.api.v1.Event';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CreatedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.CreatedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CreatedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CreatedEvent.displayName = 'proto.com.daml.ledger.api.v1.CreatedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.InterfaceView = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.InterfaceView, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.InterfaceView.displayName = 'proto.com.daml.ledger.api.v1.InterfaceView';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ArchivedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.ArchivedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ArchivedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ArchivedEvent.displayName = 'proto.com.daml.ledger.api.v1.ArchivedEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExercisedEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.ExercisedEvent.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExercisedEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExercisedEvent.displayName = 'proto.com.daml.ledger.api.v1.ExercisedEvent';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.daml.ledger.api.v1.Event.oneofGroups_ = [[1,3]];

/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.Event.EventCase = {
  EVENT_NOT_SET: 0,
  CREATED: 1,
  ARCHIVED: 3
};

/**
 * @return {proto.com.daml.ledger.api.v1.Event.EventCase}
 */
proto.com.daml.ledger.api.v1.Event.prototype.getEventCase = function() {
  return /** @type {proto.com.daml.ledger.api.v1.Event.EventCase} */(jspb.Message.computeOneofCase(this, proto.com.daml.ledger.api.v1.Event.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.Event.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.Event.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.Event} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Event.toObject = function(includeInstance, msg) {
  var f, obj = {
    created: (f = msg.getCreated()) && proto.com.daml.ledger.api.v1.CreatedEvent.toObject(includeInstance, f),
    archived: (f = msg.getArchived()) && proto.com.daml.ledger.api.v1.ArchivedEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.Event}
 */
proto.com.daml.ledger.api.v1.Event.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.Event;
  return proto.com.daml.ledger.api.v1.Event.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.Event} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.Event}
 */
proto.com.daml.ledger.api.v1.Event.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.daml.ledger.api.v1.CreatedEvent;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.CreatedEvent.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 3:
      var value = new proto.com.daml.ledger.api.v1.ArchivedEvent;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ArchivedEvent.deserializeBinaryFromReader);
      msg.setArchived(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.Event.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.Event.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.Event} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Event.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.daml.ledger.api.v1.CreatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getArchived();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.daml.ledger.api.v1.ArchivedEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional CreatedEvent created = 1;
 * @return {?proto.com.daml.ledger.api.v1.CreatedEvent}
 */
proto.com.daml.ledger.api.v1.Event.prototype.getCreated = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.CreatedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.CreatedEvent, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.CreatedEvent|undefined} value */
proto.com.daml.ledger.api.v1.Event.prototype.setCreated = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.com.daml.ledger.api.v1.Event.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Event.prototype.clearCreated = function() {
  this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Event.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ArchivedEvent archived = 3;
 * @return {?proto.com.daml.ledger.api.v1.ArchivedEvent}
 */
proto.com.daml.ledger.api.v1.Event.prototype.getArchived = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ArchivedEvent} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ArchivedEvent, 3));
};


/** @param {?proto.com.daml.ledger.api.v1.ArchivedEvent|undefined} value */
proto.com.daml.ledger.api.v1.Event.prototype.setArchived = function(value) {
  jspb.Message.setOneofWrapperField(this, 3, proto.com.daml.ledger.api.v1.Event.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Event.prototype.clearArchived = function() {
  this.setArchived(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Event.prototype.hasArchived = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.CreatedEvent.repeatedFields_ = [11,5,8,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CreatedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CreatedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CreatedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateId: (f = msg.getTemplateId()) && com_daml_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    contractKey: (f = msg.getContractKey()) && com_daml_ledger_api_v1_value_pb.Value.toObject(includeInstance, f),
    createArguments: (f = msg.getCreateArguments()) && com_daml_ledger_api_v1_value_pb.Record.toObject(includeInstance, f),
    interfaceViewsList: jspb.Message.toObjectList(msg.getInterfaceViewsList(),
    proto.com.daml.ledger.api.v1.InterfaceView.toObject, includeInstance),
    witnessPartiesList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    signatoriesList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    observersList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    agreementText: (f = msg.getAgreementText()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    metadata: (f = msg.getMetadata()) && com_daml_ledger_api_v1_contract_metadata_pb.ContractMetadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CreatedEvent}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CreatedEvent;
  return proto.com.daml.ledger.api.v1.CreatedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CreatedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CreatedEvent}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractId(value);
      break;
    case 3:
      var value = new com_daml_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setTemplateId(value);
      break;
    case 7:
      var value = new com_daml_ledger_api_v1_value_pb.Value;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Value.deserializeBinaryFromReader);
      msg.setContractKey(value);
      break;
    case 4:
      var value = new com_daml_ledger_api_v1_value_pb.Record;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Record.deserializeBinaryFromReader);
      msg.setCreateArguments(value);
      break;
    case 11:
      var value = new proto.com.daml.ledger.api.v1.InterfaceView;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.InterfaceView.deserializeBinaryFromReader);
      msg.addInterfaceViews(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addWitnessParties(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addSignatories(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addObservers(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setAgreementText(value);
      break;
    case 10:
      var value = new com_daml_ledger_api_v1_contract_metadata_pb.ContractMetadata;
      reader.readMessage(value,com_daml_ledger_api_v1_contract_metadata_pb.ContractMetadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CreatedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CreatedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CreatedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_daml_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getContractKey();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      com_daml_ledger_api_v1_value_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getCreateArguments();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      com_daml_ledger_api_v1_value_pb.Record.serializeBinaryToWriter
    );
  }
  f = message.getInterfaceViewsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      11,
      f,
      proto.com.daml.ledger.api.v1.InterfaceView.serializeBinaryToWriter
    );
  }
  f = message.getWitnessPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getSignatoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getObserversList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getAgreementText();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      com_daml_ledger_api_v1_contract_metadata_pb.ContractMetadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_id = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getContractId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setContractId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Identifier template_id = 3;
 * @return {?proto.com.daml.ledger.api.v1.Identifier}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getTemplateId = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Identifier, 3));
};


/** @param {?proto.com.daml.ledger.api.v1.Identifier|undefined} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setTemplateId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearTemplateId = function() {
  this.setTemplateId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.hasTemplateId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Value contract_key = 7;
 * @return {?proto.com.daml.ledger.api.v1.Value}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getContractKey = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Value} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Value, 7));
};


/** @param {?proto.com.daml.ledger.api.v1.Value|undefined} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setContractKey = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearContractKey = function() {
  this.setContractKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.hasContractKey = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional Record create_arguments = 4;
 * @return {?proto.com.daml.ledger.api.v1.Record}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getCreateArguments = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Record} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Record, 4));
};


/** @param {?proto.com.daml.ledger.api.v1.Record|undefined} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setCreateArguments = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearCreateArguments = function() {
  this.setCreateArguments(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.hasCreateArguments = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated InterfaceView interface_views = 11;
 * @return {!Array<!proto.com.daml.ledger.api.v1.InterfaceView>}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getInterfaceViewsList = function() {
  return /** @type{!Array<!proto.com.daml.ledger.api.v1.InterfaceView>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.daml.ledger.api.v1.InterfaceView, 11));
};


/** @param {!Array<!proto.com.daml.ledger.api.v1.InterfaceView>} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setInterfaceViewsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 11, value);
};


/**
 * @param {!proto.com.daml.ledger.api.v1.InterfaceView=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.daml.ledger.api.v1.InterfaceView}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.addInterfaceViews = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 11, opt_value, proto.com.daml.ledger.api.v1.InterfaceView, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearInterfaceViewsList = function() {
  this.setInterfaceViewsList([]);
};


/**
 * repeated string witness_parties = 5;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getWitnessPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setWitnessPartiesList = function(value) {
  jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.addWitnessParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearWitnessPartiesList = function() {
  this.setWitnessPartiesList([]);
};


/**
 * repeated string signatories = 8;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getSignatoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setSignatoriesList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.addSignatories = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearSignatoriesList = function() {
  this.setSignatoriesList([]);
};


/**
 * repeated string observers = 9;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getObserversList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setObserversList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.addObservers = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearObserversList = function() {
  this.setObserversList([]);
};


/**
 * optional google.protobuf.StringValue agreement_text = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getAgreementText = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/** @param {?proto.google.protobuf.StringValue|undefined} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setAgreementText = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearAgreementText = function() {
  this.setAgreementText(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.hasAgreementText = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ContractMetadata metadata = 10;
 * @return {?proto.com.daml.ledger.api.v1.ContractMetadata}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.getMetadata = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ContractMetadata} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_contract_metadata_pb.ContractMetadata, 10));
};


/** @param {?proto.com.daml.ledger.api.v1.ContractMetadata|undefined} value */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.setMetadata = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.clearMetadata = function() {
  this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CreatedEvent.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 10) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.InterfaceView.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.InterfaceView} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.InterfaceView.toObject = function(includeInstance, msg) {
  var f, obj = {
    interfaceId: (f = msg.getInterfaceId()) && com_daml_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    viewStatus: (f = msg.getViewStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f),
    viewValue: (f = msg.getViewValue()) && com_daml_ledger_api_v1_value_pb.Record.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.InterfaceView}
 */
proto.com.daml.ledger.api.v1.InterfaceView.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.InterfaceView;
  return proto.com.daml.ledger.api.v1.InterfaceView.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.InterfaceView} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.InterfaceView}
 */
proto.com.daml.ledger.api.v1.InterfaceView.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_daml_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setInterfaceId(value);
      break;
    case 2:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setViewStatus(value);
      break;
    case 3:
      var value = new com_daml_ledger_api_v1_value_pb.Record;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Record.deserializeBinaryFromReader);
      msg.setViewValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.InterfaceView.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.InterfaceView} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.InterfaceView.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInterfaceId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_daml_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getViewStatus();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getViewValue();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_daml_ledger_api_v1_value_pb.Record.serializeBinaryToWriter
    );
  }
};


/**
 * optional Identifier interface_id = 1;
 * @return {?proto.com.daml.ledger.api.v1.Identifier}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.getInterfaceId = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Identifier, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.Identifier|undefined} value */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.setInterfaceId = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.clearInterfaceId = function() {
  this.setInterfaceId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.hasInterfaceId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.rpc.Status view_status = 2;
 * @return {?proto.google.rpc.Status}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.getViewStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 2));
};


/** @param {?proto.google.rpc.Status|undefined} value */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.setViewStatus = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.clearViewStatus = function() {
  this.setViewStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.hasViewStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Record view_value = 3;
 * @return {?proto.com.daml.ledger.api.v1.Record}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.getViewValue = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Record} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Record, 3));
};


/** @param {?proto.com.daml.ledger.api.v1.Record|undefined} value */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.setViewValue = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.clearViewValue = function() {
  this.setViewValue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.InterfaceView.prototype.hasViewValue = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ArchivedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ArchivedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateId: (f = msg.getTemplateId()) && com_daml_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    witnessPartiesList: (f = jspb.Message.getRepeatedField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ArchivedEvent}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ArchivedEvent;
  return proto.com.daml.ledger.api.v1.ArchivedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ArchivedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ArchivedEvent}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractId(value);
      break;
    case 3:
      var value = new com_daml_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setTemplateId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.addWitnessParties(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ArchivedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ArchivedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_daml_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getWitnessPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      4,
      f
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_id = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.getContractId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.setContractId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Identifier template_id = 3;
 * @return {?proto.com.daml.ledger.api.v1.Identifier}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.getTemplateId = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Identifier, 3));
};


/** @param {?proto.com.daml.ledger.api.v1.Identifier|undefined} value */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.setTemplateId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.clearTemplateId = function() {
  this.setTemplateId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.hasTemplateId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated string witness_parties = 4;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.getWitnessPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.setWitnessPartiesList = function(value) {
  jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.addWitnessParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.ArchivedEvent.prototype.clearWitnessPartiesList = function() {
  this.setWitnessPartiesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.repeatedFields_ = [7,10,11];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExercisedEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExercisedEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contractId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    templateId: (f = msg.getTemplateId()) && com_daml_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    interfaceId: (f = msg.getInterfaceId()) && com_daml_ledger_api_v1_value_pb.Identifier.toObject(includeInstance, f),
    choice: jspb.Message.getFieldWithDefault(msg, 5, ""),
    choiceArgument: (f = msg.getChoiceArgument()) && com_daml_ledger_api_v1_value_pb.Value.toObject(includeInstance, f),
    actingPartiesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    consuming: jspb.Message.getBooleanFieldWithDefault(msg, 8, false),
    witnessPartiesList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    childEventIdsList: (f = jspb.Message.getRepeatedField(msg, 11)) == null ? undefined : f,
    exerciseResult: (f = msg.getExerciseResult()) && com_daml_ledger_api_v1_value_pb.Value.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExercisedEvent}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExercisedEvent;
  return proto.com.daml.ledger.api.v1.ExercisedEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExercisedEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExercisedEvent}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContractId(value);
      break;
    case 3:
      var value = new com_daml_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setTemplateId(value);
      break;
    case 13:
      var value = new com_daml_ledger_api_v1_value_pb.Identifier;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Identifier.deserializeBinaryFromReader);
      msg.setInterfaceId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setChoice(value);
      break;
    case 6:
      var value = new com_daml_ledger_api_v1_value_pb.Value;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Value.deserializeBinaryFromReader);
      msg.setChoiceArgument(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addActingParties(value);
      break;
    case 8:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setConsuming(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addWitnessParties(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.addChildEventIds(value);
      break;
    case 12:
      var value = new com_daml_ledger_api_v1_value_pb.Value;
      reader.readMessage(value,com_daml_ledger_api_v1_value_pb.Value.deserializeBinaryFromReader);
      msg.setExerciseResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExercisedEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExercisedEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContractId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTemplateId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      com_daml_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getInterfaceId();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      com_daml_ledger_api_v1_value_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getChoice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getChoiceArgument();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      com_daml_ledger_api_v1_value_pb.Value.serializeBinaryToWriter
    );
  }
  f = message.getActingPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getConsuming();
  if (f) {
    writer.writeBool(
      8,
      f
    );
  }
  f = message.getWitnessPartiesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getChildEventIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      11,
      f
    );
  }
  f = message.getExerciseResult();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      com_daml_ledger_api_v1_value_pb.Value.serializeBinaryToWriter
    );
  }
};


/**
 * optional string event_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getEventId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setEventId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contract_id = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getContractId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setContractId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional Identifier template_id = 3;
 * @return {?proto.com.daml.ledger.api.v1.Identifier}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getTemplateId = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Identifier, 3));
};


/** @param {?proto.com.daml.ledger.api.v1.Identifier|undefined} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setTemplateId = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearTemplateId = function() {
  this.setTemplateId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.hasTemplateId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Identifier interface_id = 13;
 * @return {?proto.com.daml.ledger.api.v1.Identifier}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getInterfaceId = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Identifier} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Identifier, 13));
};


/** @param {?proto.com.daml.ledger.api.v1.Identifier|undefined} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setInterfaceId = function(value) {
  jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearInterfaceId = function() {
  this.setInterfaceId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.hasInterfaceId = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional string choice = 5;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getChoice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setChoice = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Value choice_argument = 6;
 * @return {?proto.com.daml.ledger.api.v1.Value}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getChoiceArgument = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Value} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Value, 6));
};


/** @param {?proto.com.daml.ledger.api.v1.Value|undefined} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setChoiceArgument = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearChoiceArgument = function() {
  this.setChoiceArgument(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.hasChoiceArgument = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated string acting_parties = 7;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getActingPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setActingPartiesList = function(value) {
  jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.addActingParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearActingPartiesList = function() {
  this.setActingPartiesList([]);
};


/**
 * optional bool consuming = 8;
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getConsuming = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 8, false));
};


/** @param {boolean} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setConsuming = function(value) {
  jspb.Message.setProto3BooleanField(this, 8, value);
};


/**
 * repeated string witness_parties = 10;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getWitnessPartiesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setWitnessPartiesList = function(value) {
  jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.addWitnessParties = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearWitnessPartiesList = function() {
  this.setWitnessPartiesList([]);
};


/**
 * repeated string child_event_ids = 11;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getChildEventIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 11));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setChildEventIdsList = function(value) {
  jspb.Message.setField(this, 11, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.addChildEventIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 11, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearChildEventIdsList = function() {
  this.setChildEventIdsList([]);
};


/**
 * optional Value exercise_result = 12;
 * @return {?proto.com.daml.ledger.api.v1.Value}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.getExerciseResult = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.Value} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_value_pb.Value, 12));
};


/** @param {?proto.com.daml.ledger.api.v1.Value|undefined} value */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.setExerciseResult = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.clearExerciseResult = function() {
  this.setExerciseResult(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExercisedEvent.prototype.hasExerciseResult = function() {
  return jspb.Message.getField(this, 12) != null;
};


goog.object.extend(exports, proto.com.daml.ledger.api.v1);
