/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.DurationSupport', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.OffsetSupport', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.CommandDeduplicationType', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.CommitterEventLogType', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalContractIds', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalContractIds.ContractIdV1Support', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalFeatures', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.ExperimentalStaticTime', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalFeatures, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalFeatures.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalFeatures';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalStaticTime, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalStaticTime.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalStaticTime';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.displayName = 'proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.displayName = 'proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalContractIds, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalContractIds.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalContractIds';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.displayName = 'proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalFeatures.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalFeatures} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.toObject = function(includeInstance, msg) {
  var f, obj = {
    selfServiceErrorCodes: (f = msg.getSelfServiceErrorCodes()) && proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.toObject(includeInstance, f),
    staticTime: (f = msg.getStaticTime()) && proto.com.daml.ledger.api.v1.ExperimentalStaticTime.toObject(includeInstance, f),
    commandDeduplication: (f = msg.getCommandDeduplication()) && proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.toObject(includeInstance, f),
    optionalLedgerId: (f = msg.getOptionalLedgerId()) && proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.toObject(includeInstance, f),
    contractIds: (f = msg.getContractIds()) && proto.com.daml.ledger.api.v1.ExperimentalContractIds.toObject(includeInstance, f),
    committerEventLog: (f = msg.getCommitterEventLog()) && proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.toObject(includeInstance, f),
    explicitDisclosure: (f = msg.getExplicitDisclosure()) && proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalFeatures}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalFeatures;
  return proto.com.daml.ledger.api.v1.ExperimentalFeatures.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalFeatures} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalFeatures}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.deserializeBinaryFromReader);
      msg.setSelfServiceErrorCodes(value);
      break;
    case 2:
      var value = new proto.com.daml.ledger.api.v1.ExperimentalStaticTime;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ExperimentalStaticTime.deserializeBinaryFromReader);
      msg.setStaticTime(value);
      break;
    case 3:
      var value = new proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.deserializeBinaryFromReader);
      msg.setCommandDeduplication(value);
      break;
    case 4:
      var value = new proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.deserializeBinaryFromReader);
      msg.setOptionalLedgerId(value);
      break;
    case 5:
      var value = new proto.com.daml.ledger.api.v1.ExperimentalContractIds;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ExperimentalContractIds.deserializeBinaryFromReader);
      msg.setContractIds(value);
      break;
    case 6:
      var value = new proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.deserializeBinaryFromReader);
      msg.setCommitterEventLog(value);
      break;
    case 7:
      var value = new proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.deserializeBinaryFromReader);
      msg.setExplicitDisclosure(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalFeatures.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalFeatures} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSelfServiceErrorCodes();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.serializeBinaryToWriter
    );
  }
  f = message.getStaticTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.com.daml.ledger.api.v1.ExperimentalStaticTime.serializeBinaryToWriter
    );
  }
  f = message.getCommandDeduplication();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.serializeBinaryToWriter
    );
  }
  f = message.getOptionalLedgerId();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.serializeBinaryToWriter
    );
  }
  f = message.getContractIds();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.daml.ledger.api.v1.ExperimentalContractIds.serializeBinaryToWriter
    );
  }
  f = message.getCommitterEventLog();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.serializeBinaryToWriter
    );
  }
  f = message.getExplicitDisclosure();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.serializeBinaryToWriter
    );
  }
};


/**
 * optional ExperimentalSelfServiceErrorCodes self_service_error_codes = 1;
 * @return {?proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getSelfServiceErrorCodes = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setSelfServiceErrorCodes = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearSelfServiceErrorCodes = function() {
  this.setSelfServiceErrorCodes(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasSelfServiceErrorCodes = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ExperimentalStaticTime static_time = 2;
 * @return {?proto.com.daml.ledger.api.v1.ExperimentalStaticTime}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getStaticTime = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExperimentalStaticTime} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ExperimentalStaticTime, 2));
};


/** @param {?proto.com.daml.ledger.api.v1.ExperimentalStaticTime|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setStaticTime = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearStaticTime = function() {
  this.setStaticTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasStaticTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CommandDeduplicationFeatures command_deduplication = 3;
 * @return {?proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getCommandDeduplication = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures, 3));
};


/** @param {?proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setCommandDeduplication = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearCommandDeduplication = function() {
  this.setCommandDeduplication(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasCommandDeduplication = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ExperimentalOptionalLedgerId optional_ledger_id = 4;
 * @return {?proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getOptionalLedgerId = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId, 4));
};


/** @param {?proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setOptionalLedgerId = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearOptionalLedgerId = function() {
  this.setOptionalLedgerId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasOptionalLedgerId = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ExperimentalContractIds contract_ids = 5;
 * @return {?proto.com.daml.ledger.api.v1.ExperimentalContractIds}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getContractIds = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExperimentalContractIds} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ExperimentalContractIds, 5));
};


/** @param {?proto.com.daml.ledger.api.v1.ExperimentalContractIds|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setContractIds = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearContractIds = function() {
  this.setContractIds(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasContractIds = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ExperimentalCommitterEventLog committer_event_log = 6;
 * @return {?proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getCommitterEventLog = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog, 6));
};


/** @param {?proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setCommitterEventLog = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearCommitterEventLog = function() {
  this.setCommitterEventLog(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasCommitterEventLog = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ExperimentalExplicitDisclosure explicit_disclosure = 7;
 * @return {?proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.getExplicitDisclosure = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure, 7));
};


/** @param {?proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure|undefined} value */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.setExplicitDisclosure = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.clearExplicitDisclosure = function() {
  this.setExplicitDisclosure(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalFeatures.prototype.hasExplicitDisclosure = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes}
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes;
  return proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes}
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalSelfServiceErrorCodes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalStaticTime.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalStaticTime} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.toObject = function(includeInstance, msg) {
  var f, obj = {
    supported: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalStaticTime}
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalStaticTime;
  return proto.com.daml.ledger.api.v1.ExperimentalStaticTime.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalStaticTime} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalStaticTime}
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSupported(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalStaticTime.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalStaticTime} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSupported();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool supported = 1;
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.prototype.getSupported = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.com.daml.ledger.api.v1.ExperimentalStaticTime.prototype.setSupported = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.toObject = function(includeInstance, msg) {
  var f, obj = {
    deduplicationPeriodSupport: (f = msg.getDeduplicationPeriodSupport()) && proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.toObject(includeInstance, f),
    deduplicationType: jspb.Message.getFieldWithDefault(msg, 2, 0),
    maxDeduplicationDurationEnforced: jspb.Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures;
  return proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport;
      reader.readMessage(value,proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.deserializeBinaryFromReader);
      msg.setDeduplicationPeriodSupport(value);
      break;
    case 2:
      var value = /** @type {!proto.com.daml.ledger.api.v1.CommandDeduplicationType} */ (reader.readEnum());
      msg.setDeduplicationType(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setMaxDeduplicationDurationEnforced(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeduplicationPeriodSupport();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.serializeBinaryToWriter
    );
  }
  f = message.getDeduplicationType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getMaxDeduplicationDurationEnforced();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional CommandDeduplicationPeriodSupport deduplication_period_support = 1;
 * @return {?proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.getDeduplicationPeriodSupport = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport} */ (
    jspb.Message.getWrapperField(this, proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport|undefined} value */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.setDeduplicationPeriodSupport = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.clearDeduplicationPeriodSupport = function() {
  this.setDeduplicationPeriodSupport(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.hasDeduplicationPeriodSupport = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional CommandDeduplicationType deduplication_type = 2;
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationType}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.getDeduplicationType = function() {
  return /** @type {!proto.com.daml.ledger.api.v1.CommandDeduplicationType} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationType} value */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.setDeduplicationType = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional bool max_deduplication_duration_enforced = 3;
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.getMaxDeduplicationDurationEnforced = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.com.daml.ledger.api.v1.CommandDeduplicationFeatures.prototype.setMaxDeduplicationDurationEnforced = function(value) {
  jspb.Message.setProto3BooleanField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId}
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId;
  return proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId}
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalOptionalLedgerId.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.toObject = function(includeInstance, msg) {
  var f, obj = {
    offsetSupport: jspb.Message.getFieldWithDefault(msg, 1, 0),
    durationSupport: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport;
  return proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.OffsetSupport} */ (reader.readEnum());
      msg.setOffsetSupport(value);
      break;
    case 2:
      var value = /** @type {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.DurationSupport} */ (reader.readEnum());
      msg.setDurationSupport(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOffsetSupport();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getDurationSupport();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.OffsetSupport = {
  OFFSET_NOT_SUPPORTED: 0,
  OFFSET_NATIVE_SUPPORT: 1,
  OFFSET_CONVERT_TO_DURATION: 2
};

/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.DurationSupport = {
  DURATION_NATIVE_SUPPORT: 0,
  DURATION_CONVERT_TO_OFFSET: 1
};

/**
 * optional OffsetSupport offset_support = 1;
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.OffsetSupport}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.prototype.getOffsetSupport = function() {
  return /** @type {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.OffsetSupport} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.OffsetSupport} value */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.prototype.setOffsetSupport = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional DurationSupport duration_support = 2;
 * @return {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.DurationSupport}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.prototype.getDurationSupport = function() {
  return /** @type {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.DurationSupport} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {!proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.DurationSupport} value */
proto.com.daml.ledger.api.v1.CommandDeduplicationPeriodSupport.prototype.setDurationSupport = function(value) {
  jspb.Message.setProto3EnumField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalContractIds.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalContractIds} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.toObject = function(includeInstance, msg) {
  var f, obj = {
    v1: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalContractIds}
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalContractIds;
  return proto.com.daml.ledger.api.v1.ExperimentalContractIds.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalContractIds} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalContractIds}
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.daml.ledger.api.v1.ExperimentalContractIds.ContractIdV1Support} */ (reader.readEnum());
      msg.setV1(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalContractIds.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalContractIds} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getV1();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.ContractIdV1Support = {
  SUFFIXED: 0,
  NON_SUFFIXED: 1
};

/**
 * optional ContractIdV1Support v1 = 1;
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalContractIds.ContractIdV1Support}
 */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.prototype.getV1 = function() {
  return /** @type {!proto.com.daml.ledger.api.v1.ExperimentalContractIds.ContractIdV1Support} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.daml.ledger.api.v1.ExperimentalContractIds.ContractIdV1Support} value */
proto.com.daml.ledger.api.v1.ExperimentalContractIds.prototype.setV1 = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.toObject = function(includeInstance, msg) {
  var f, obj = {
    eventLogType: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog}
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog;
  return proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog}
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.CommitterEventLogType} */ (reader.readEnum());
      msg.setEventLogType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEventLogType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.CommitterEventLogType = {
  CENTRALIZED: 0,
  DISTRIBUTED: 1
};

/**
 * optional CommitterEventLogType event_log_type = 1;
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.CommitterEventLogType}
 */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.prototype.getEventLogType = function() {
  return /** @type {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.CommitterEventLogType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.CommitterEventLogType} value */
proto.com.daml.ledger.api.v1.ExperimentalCommitterEventLog.prototype.setEventLogType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.toObject = function(includeInstance, msg) {
  var f, obj = {
    supported: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure}
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure;
  return proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure}
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSupported(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSupported();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool supported = 1;
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.prototype.getSupported = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.com.daml.ledger.api.v1.ExperimentalExplicitDisclosure.prototype.setSupported = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.CommandDeduplicationType = {
  ASYNC_ONLY: 0,
  ASYNC_AND_CONCURRENT_SYNC: 1
};

goog.object.extend(exports, proto.com.daml.ledger.api.v1);
