/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var com_daml_ledger_api_v1_event_pb = require('../../../../../com/daml/ledger/api/v1/event_pb.js');
goog.object.extend(proto, com_daml_ledger_api_v1_event_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.com.daml.ledger.api.v1.Transaction', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.TransactionTree', null, global);
goog.exportSymbol('proto.com.daml.ledger.api.v1.TreeEvent', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.TransactionTree = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.TransactionTree.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.TransactionTree, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.TransactionTree.displayName = 'proto.com.daml.ledger.api.v1.TransactionTree';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.TreeEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.daml.ledger.api.v1.TreeEvent.oneofGroups_);
};
goog.inherits(proto.com.daml.ledger.api.v1.TreeEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.TreeEvent.displayName = 'proto.com.daml.ledger.api.v1.TreeEvent';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.daml.ledger.api.v1.Transaction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.daml.ledger.api.v1.Transaction.repeatedFields_, null);
};
goog.inherits(proto.com.daml.ledger.api.v1.Transaction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.daml.ledger.api.v1.Transaction.displayName = 'proto.com.daml.ledger.api.v1.Transaction';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.TransactionTree.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.TransactionTree.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.TransactionTree} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.TransactionTree.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    commandId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    workflowId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    effectiveAt: (f = msg.getEffectiveAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    offset: jspb.Message.getFieldWithDefault(msg, 6, ""),
    eventsByIdMap: (f = msg.getEventsByIdMap()) ? f.toObject(includeInstance, proto.com.daml.ledger.api.v1.TreeEvent.toObject) : [],
    rootEventIdsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.TransactionTree}
 */
proto.com.daml.ledger.api.v1.TransactionTree.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.TransactionTree;
  return proto.com.daml.ledger.api.v1.TransactionTree.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.TransactionTree} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.TransactionTree}
 */
proto.com.daml.ledger.api.v1.TransactionTree.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEffectiveAt(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOffset(value);
      break;
    case 7:
      var value = msg.getEventsByIdMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.com.daml.ledger.api.v1.TreeEvent.deserializeBinaryFromReader, "");
         });
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addRootEventIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.TransactionTree.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.TransactionTree} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.TransactionTree.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCommandId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEffectiveAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getOffset();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEventsByIdMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.com.daml.ledger.api.v1.TreeEvent.serializeBinaryToWriter);
  }
  f = message.getRootEventIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
};


/**
 * optional string transaction_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.setTransactionId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string command_id = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getCommandId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.setCommandId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string workflow_id = 3;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.setWorkflowId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp effective_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getEffectiveAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.setEffectiveAt = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.clearEffectiveAt = function() {
  this.setEffectiveAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.hasEffectiveAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string offset = 6;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.setOffset = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * map<string, TreeEvent> events_by_id = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.com.daml.ledger.api.v1.TreeEvent>}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getEventsByIdMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.com.daml.ledger.api.v1.TreeEvent>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.com.daml.ledger.api.v1.TreeEvent));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.clearEventsByIdMap = function() {
  this.getEventsByIdMap().clear();
};


/**
 * repeated string root_event_ids = 8;
 * @return {!Array<string>}
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.getRootEventIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/** @param {!Array<string>} value */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.setRootEventIdsList = function(value) {
  jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.addRootEventIds = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.TransactionTree.prototype.clearRootEventIdsList = function() {
  this.setRootEventIdsList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.daml.ledger.api.v1.TreeEvent.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.com.daml.ledger.api.v1.TreeEvent.KindCase = {
  KIND_NOT_SET: 0,
  CREATED: 1,
  EXERCISED: 2
};

/**
 * @return {proto.com.daml.ledger.api.v1.TreeEvent.KindCase}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.getKindCase = function() {
  return /** @type {proto.com.daml.ledger.api.v1.TreeEvent.KindCase} */(jspb.Message.computeOneofCase(this, proto.com.daml.ledger.api.v1.TreeEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.TreeEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.TreeEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.TreeEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    created: (f = msg.getCreated()) && com_daml_ledger_api_v1_event_pb.CreatedEvent.toObject(includeInstance, f),
    exercised: (f = msg.getExercised()) && com_daml_ledger_api_v1_event_pb.ExercisedEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.TreeEvent}
 */
proto.com.daml.ledger.api.v1.TreeEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.TreeEvent;
  return proto.com.daml.ledger.api.v1.TreeEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.TreeEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.TreeEvent}
 */
proto.com.daml.ledger.api.v1.TreeEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new com_daml_ledger_api_v1_event_pb.CreatedEvent;
      reader.readMessage(value,com_daml_ledger_api_v1_event_pb.CreatedEvent.deserializeBinaryFromReader);
      msg.setCreated(value);
      break;
    case 2:
      var value = new com_daml_ledger_api_v1_event_pb.ExercisedEvent;
      reader.readMessage(value,com_daml_ledger_api_v1_event_pb.ExercisedEvent.deserializeBinaryFromReader);
      msg.setExercised(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.TreeEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.TreeEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.TreeEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCreated();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      com_daml_ledger_api_v1_event_pb.CreatedEvent.serializeBinaryToWriter
    );
  }
  f = message.getExercised();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      com_daml_ledger_api_v1_event_pb.ExercisedEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional CreatedEvent created = 1;
 * @return {?proto.com.daml.ledger.api.v1.CreatedEvent}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.getCreated = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.CreatedEvent} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_event_pb.CreatedEvent, 1));
};


/** @param {?proto.com.daml.ledger.api.v1.CreatedEvent|undefined} value */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.setCreated = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.com.daml.ledger.api.v1.TreeEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.clearCreated = function() {
  this.setCreated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.hasCreated = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ExercisedEvent exercised = 2;
 * @return {?proto.com.daml.ledger.api.v1.ExercisedEvent}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.getExercised = function() {
  return /** @type{?proto.com.daml.ledger.api.v1.ExercisedEvent} */ (
    jspb.Message.getWrapperField(this, com_daml_ledger_api_v1_event_pb.ExercisedEvent, 2));
};


/** @param {?proto.com.daml.ledger.api.v1.ExercisedEvent|undefined} value */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.setExercised = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.com.daml.ledger.api.v1.TreeEvent.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.clearExercised = function() {
  this.setExercised(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.TreeEvent.prototype.hasExercised = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.daml.ledger.api.v1.Transaction.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.toObject = function(opt_includeInstance) {
  return proto.com.daml.ledger.api.v1.Transaction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.daml.ledger.api.v1.Transaction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Transaction.toObject = function(includeInstance, msg) {
  var f, obj = {
    transactionId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    commandId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    workflowId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    effectiveAt: (f = msg.getEffectiveAt()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    eventsList: jspb.Message.toObjectList(msg.getEventsList(),
    com_daml_ledger_api_v1_event_pb.Event.toObject, includeInstance),
    offset: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.daml.ledger.api.v1.Transaction}
 */
proto.com.daml.ledger.api.v1.Transaction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.daml.ledger.api.v1.Transaction;
  return proto.com.daml.ledger.api.v1.Transaction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.daml.ledger.api.v1.Transaction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.daml.ledger.api.v1.Transaction}
 */
proto.com.daml.ledger.api.v1.Transaction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTransactionId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkflowId(value);
      break;
    case 4:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEffectiveAt(value);
      break;
    case 5:
      var value = new com_daml_ledger_api_v1_event_pb.Event;
      reader.readMessage(value,com_daml_ledger_api_v1_event_pb.Event.deserializeBinaryFromReader);
      msg.addEvents(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOffset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.daml.ledger.api.v1.Transaction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.daml.ledger.api.v1.Transaction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.daml.ledger.api.v1.Transaction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTransactionId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCommandId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWorkflowId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getEffectiveAt();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEventsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      com_daml_ledger_api_v1_event_pb.Event.serializeBinaryToWriter
    );
  }
  f = message.getOffset();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string transaction_id = 1;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.getTransactionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Transaction.prototype.setTransactionId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string command_id = 2;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.getCommandId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Transaction.prototype.setCommandId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string workflow_id = 3;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.getWorkflowId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Transaction.prototype.setWorkflowId = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp effective_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.getEffectiveAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.com.daml.ledger.api.v1.Transaction.prototype.setEffectiveAt = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.clearEffectiveAt = function() {
  this.setEffectiveAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.hasEffectiveAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated Event events = 5;
 * @return {!Array<!proto.com.daml.ledger.api.v1.Event>}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.getEventsList = function() {
  return /** @type{!Array<!proto.com.daml.ledger.api.v1.Event>} */ (
    jspb.Message.getRepeatedWrapperField(this, com_daml_ledger_api_v1_event_pb.Event, 5));
};


/** @param {!Array<!proto.com.daml.ledger.api.v1.Event>} value */
proto.com.daml.ledger.api.v1.Transaction.prototype.setEventsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.com.daml.ledger.api.v1.Event=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.daml.ledger.api.v1.Event}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.addEvents = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.com.daml.ledger.api.v1.Event, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.clearEventsList = function() {
  this.setEventsList([]);
};


/**
 * optional string offset = 6;
 * @return {string}
 */
proto.com.daml.ledger.api.v1.Transaction.prototype.getOffset = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.com.daml.ledger.api.v1.Transaction.prototype.setOffset = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.com.daml.ledger.api.v1);
